### ISSUE TITLE
warc2preprocess dropping records

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#110]
`/fs/meili0/faheem/paracrawl/ebay/pl-de/transient/visitopolskie`

second record in `concat.warc.xz` is skipped

**Comment by lpla** [comment]
Which Record-ID or Target-URI is? I don't see it

In any case, it could be that latest `bitextor-warc2preprocess.py` from master works. I changed `warc` Python library. Now we are using `warcio` instead of `warc` from `warc3-wet`.

I will run `master` with this `concat.warc.xz` but I need to know the exact record we are skipping.

**Comment by wwaites** [comment]
it is the second record in the file

**Comment by lpla** [comment]
I will assume is this one:

WARC/1.0
WARC-Record-ID: <urn:uuid:0d6d20f6-3274-11e9-9185-d0946606fc67>
Content-Length: 22191
Content-Type: application/http; msgtype=response
WARC-Date: 2019-02-16T19:17:54Z


Yes, in Faheem tests it is skipped. In my tests using latest `master` branch code it is not. So, please, pull changes and report any other WARC issue.
