### ISSUE TITLE
idnum += 1

### ISSUE THREAD

**Issue by kirefu** [bitextor/bitextor#116]
Hi,

https://github.com/bitextor/bitextor/blob/e18fdd95bc20a07dec27969f30b1606932e99e56/bitextor-buildTMX-dedup.py#L128

Just wanted to make sure that this line is meant to be where it is, as supposed the being contained after the if curid != previd statement.

Faheem

**Comment by mbanon** [comment]
@kirefu 
This was reported by @sortiz before last corpora release, and I thought @lpla fixed it, but it seems not.

**Comment by lpla** [comment]
I can't find where or what was exactly reported before, but in any case, this counter is increased by each read line from `??-??.sent.xz` parallel sentences generated by Bitextor. So, in case of duplicated sentences, we print last occurrence `idnum`, which implicitly gives how many duplicates we had per sentence. I thought this was the expected behavior.

**Comment by mbanon** [comment]
@lpla We reported by email.  "Executar la part final del pipeline" thread, starting 22/02/19. Reported 6/3/19 13:28, @sortiz  sent a fixed file on 2019-03-06 14:03

I'm forwarding you the email again.

**Comment by kpu** [comment]
It just seems weird to give a corpus out with non-consecutive idnums.  Aren't we mostly giving number of duplicates by number of urls?  (And probably being inconsistent about within-document duplicates now that Philipp and Hieu are merging)

**Comment by lpla** [comment]
That commit I referenced makes that "build TMX" now outputs consecutive idnums. As @mbanon said, it was reported by mail, even fixed code was attached but I forgot about it.
