### ISSUE TITLE
Feature Request: Could you describe the way to handle non-Europian languages?

### ISSUE THREAD

**Issue by sugiyamath** [bitextor/bitextor#120]
I'm frustrated that bitextor is only used for Europian languages, but a lot of people want this kind of automatic corpus generation tool even if they're not Europian people. However, I'm not sure how to do it because of its complexity of the source codes.

I've searched for this kind of tools, but couldn't find it better than bitextor.

Could you support non-Europian languages and describe it on README.md or wiki?

**Comment by lpla** [comment]
Bitextor is not designed for European languages only. We have been developing it with those because we are in the [Paracrawl European project](https://paracrawl.eu/), but code should be general enough to work with any language (pair) if you provide the language dependent resources needed.

The first resources you need to prepare are the tokenizers. Bitextor options for that are explained in [README.md](https://github.com/bitextor/bitextor/blob/master/docs/README.md#basic-variables):
- word tokenizer: we mainly use Moses tokenizer
- sentence splitter: we use Moses or NLTK one

And, depending on [which document aligner option you use in Bitextor](https://github.com/bitextor/bitextor/blob/master/docs/README.md#variables-for-document-alignment), you will need to:
- provide a MT system command (a Moses system, for example) or 
- parallel corpus to train a dictionary/bilingual lexica (we usually choose a clean medium-sized one from http://opus.nlpl.eu/).

This is the bare minimum resources you need to make Bitextor work. You could provide more corpus to [train a Bicleaner model](https://github.com/bitextor/bitextor/blob/master/docs/README.md#variables-for-parallel-data-filtering), for example.

Of course, you will need to set a source of data, like a domain URL using the ["hosts" setting](https://github.com/bitextor/bitextor/blob/master/docs/README.md#variables-defining-data-sources).

**Comment by lpla** [comment]
New Wiki entry: https://github.com/bitextor/bitextor/wiki/Using-Bitextor-for-non-European-languages
