### ISSUE TITLE
How to crawl the entire web by using bitextor?

### ISSUE THREAD

**Issue by sugiyamath** [bitextor/bitextor#121]
I've tried to use bitextor to build my own corpus, however, it might support only specific hosts in the config file.

Would you please tell me how to gather the parallel corpus from entire the web like a search engine's crawler by using bitextor? 

In addition, I want to insert the parallel sentences into ```lang1-lang2.sent.xz``` continuously while the crawler is running because if we will gather data from entire the web, it takes a long time to finish gathering all possible web sites, so want to generate the parallel corpus at the same time, or I'd prefer the separated files like host1.sent.xz, host2.sent.xz, and so on.

I'd like to know whether it's supported feature or not. (I'm sorry for my terrible English writing.)

**Comment by lpla** [comment]
I think I don't understand quite well, but I am gonna try.

We need to specify a set of hosts/domains (not restricted by robots.txt) to download all the content into a WARC using any of the three supported crawlers. If you don't want to crawl using our supported engines, you can do it externally and then plug your WARCs in Bitextor to process them. This is explained in README.md

I don't know what do you mean by "entire the web", if you mean a simple domain or the whole "Internet". If it is the latter, you are lucky because that's what we are doing in Paracrawl 2 (https://paracrawl.eu/) using The Internet Archive (which is in WARC format).

But Bitextor can't obtain sentence pairs "on-the-fly"/actively, as he needs the whole data to be already downloaded and processed to pair documents (HTMLs) and find parallel sentences.

For example, imagine that you are downloading a simple domain with a couple of pair documents in "en-fr" languages. If crawler downloads all English files first and French files at the end, and let's say that we do this kind of "on-the-fly" alignment output at the middle of the crawling process trying to pair these English documents, we won't find anything as we didn't download French documents yet.

The same applies for a huge WARC file. So, no, we don't support this countinuous/active/"on-the-fly" processing given the way we align documents and sentences.

**Comment by sugiyamath** [comment]
Thank you so much. I'll check it.

**Comment by hieuhoang** [comment]
We have a list of millions of hosts with estimates of how much data there are in each language.
   http://statmt.org/hieu/paracrawl/langstats.all.gz
This can be used to produce a set of hosts to be crawled.

The config file below uses it as an example
   https://github.com/bitextor/bitextor/blob/bitextor-malign/snakemake/example/hieu/config.hu-en.yaml
