### ISSUE TITLE
Best way to continue an interrupted crawling

### ISSUE THREAD

**Issue by vince62s** [bitextor/bitextor#130]
Hello,

I would like to know:

1) if I "interrupt" a crawling with CTRL-C, can I still continue the pipeline to generate the bitexts ?

2) Can I run a kind of "continue where it stopped" crawling ?

Thanks.

**Comment by lpla** [comment]
> 1. if I "interrupt" a crawling with CTRL-C, can I still continue the pipeline to generate the bitexts ?

I think we lost that feature when we switched to Snakemake, given that if you do Ctrl+C, Snakemake "layer" is going to stop. If you want to stop the crawling after some time, you need to provide the parameter `crawlTimeLimit` in the Snakemake config file, acting as a timeout for the crawling step only, and then continuing the remaining Bitextor process.

> 2. Can I run a kind of "continue where it stopped" crawling ?

This is a WIP feature being developed in the `heritrix` branch, in which we are implementing support for the [Heritrix](https://github.com/internetarchive/heritrix3) crawler from the Internet Archive. This crawler supports resuming crawls, creating additional WARC files. Feel free to test it, and we hope we get it merged soon in `master` branch, for next 7.3 release.

**Comment by vince62s** [comment]
for 1:
There us no way I can modify the Snakemake file after CTRL+C so that it resume after the crawling step?

I'll give a try to 2. but if I could not lose a few days of crawling, that would be great.

**Comment by lpla** [comment]
Well, thinking about re-running the Snakemake after killing it, it could work but it depends on the crawler.

If you used creepy or wget, you can re-run Snakemake after killing it and it will continue because those two crawlers output WARC files directly. So Snakemake will find those files at the DAG build step and continue processing from that "partial" file, but maybe last WARC entry could be corrupt, as you may kill the process while writing files.

If you use httrack, you need to do more manual stuff, as it downloads crawled files to a temporary folder, which we convert into WARC after crawling finished. So you would need to convert that folder into WARC manually using the same scripts we use: `bitextor-webdir2warc.sh $DIRNAME`

In case you use the WIP branch `heritrix`, the web interface has an option to do a checkpoint and pause crawling, which is the most stable and clean way to do it.

**Comment by vince62s** [comment]
ok
