### ISSUE TITLE
[Installation] Destination directory

### ISSUE THREAD

**Issue by tarnh** [bitextor/bitextor#148]
I am in the last steps of finishing an ArchLinux PKGBUILD for bitextor.
[This](https://pastebin.com/zQ5TFzta) is the current state.

The only thing to fix is the install path:
`make DESTDIR="$pkgdir/" install`
ignores DESTDIR and anyway tries to write into /usr/local

**Comment by lpla** [comment]
I think that you need to use `--prefix`, but we stopped installing Bitextor after release 6.0, so probably that will be broken if you are packaging everything this way.

**Comment by tarnh** [comment]
Ok, but where is the Dockerfile located?

**Comment by lpla** [comment]
I uploaded it to master branch. It was in a private repository of Paracrawl project, sorry.

**Comment by tarnh** [comment]
Thanks, but you don't have to be sorry for that. The installation steps are a straightforward `autogen/make/make install` - everybody could figure that out.

But without support for any of
- `PREFIX=/usr`
- `make --prefix=/usr`
- `DESTDIR="$pkgdir/"`
it's impossible to safely deploy bitextor in a classical (pre-Docker) way

Please do something about it.

**Comment by lpla** [comment]
Hi @tarnh ! Sorry for taking this long since your last message, but we have been working on refactoring Bitextor installation steps lately. Check out the new instructions in https://github.com/bitextor/bitextor/blob/master/docs/INSTALL.md , which should be the way to install Bitextor in the next release.

I don't know if that way works for Arch Linux packages, but please feel free to suggest any change we could perform that might help packaging Bitextor.

**Comment by lpla** [comment]
Hi. We released Bitextor v8.1 including this change. If they are not enough to install Bitextor using a package manager, please reopen this issue.
