### ISSUE TITLE
bitextor-warc2htmlwarc.py does not process gz files correctly

### ISSUE THREAD

**Issue by bhaddow** [bitextor/bitextor#155]
It tries to open a gz file as a normal uncompressed file, and thus sees no records. See bitextor-warc2htmlwarc.py - line 137

**Comment by lpla** [comment]
This is intentional. Library `from warcio.archiveiterator import ArchiveIterator` works with a gzipped stream, as [WARC standard](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/) defines WARC as a set of individually gzipped records.

It is likely that your WARC gz file is not compressed this way. If that is the case, run `warcio recompress inputwarc.gz outputwarc.gz` in a Bash terminal and try again.

**Comment by bhaddow** [comment]
As far as I know the warc.gz file was created by the bitextor wget crawler. I will check, because it wasn't me that crawled it.

**Comment by bhaddow** [comment]
So it looks like we are an old version of bitextor-warc.py - could this be the problem?

**Comment by lpla** [comment]
Could be. We are testing some combinations of WARC compressed files and uncompressed WARCs are processed correctly by `warcio` library using latest code from `master`. This means that, to avoid checking and recompressing properly WARC files, you could try to pass an uncompressed version of your WARC or pipe it like

```
zcat mywarc.gz | python3 bitextor-warc2htmlwarc.py > wellcompressedwarc.gz
```

**Comment by bhaddow** [comment]
Thanks Leo. Will close now, assume because we are on an old version.

**Comment by lpla** [comment]
You are welcome! Let us know if you have any other issue, anytime
