### ISSUE TITLE
bitextor-build-docalign.py stuck in an infinite loop

### ISSUE THREAD

**Issue by critias** [bitextor/bitextor#171]
If the provided indices to bitextor-build-docalign.py contain a 0 as the second index in any line except the first line, it gets stuck in an infinite loop.
Looking at the code of bitextor-build-docalign.py it seems to me like it an assumption that the second index should be greater or equal to one.

I'm not sure at this point if the underlying assumption inside of bitextor-build-docalign.py is wrong that the second index should be >= 1 or if the output of bitextor-align-documents.py broken. Any ideas?

A minimal example for indices file which causes the infinite loop:
```
1       1
2       0
```

**Comment by zuny26** [comment]
Hello @critias,
what version/branch of Bitextor are you using?
I have updated that script in master branch because the code was a bit weird. However, it is not expected to have 0 in the indices file, since the document aligner counts documents from 1.
Was there a 0 in the indices file produced by Bitextor, or did you create this file manually to test the script?

**Comment by critias** [comment]
Hi @zuny26,
I'm using the latest version of the 7.x branch. Last week I also tried the bitextor-build-docalign.py script from the master branch, which got still stuck in an infinite loop.
I uploaded a minimal example of the data and config which triggers that bug for me: 
http://www-i6.informatik.rwth-aachen.de/~peter/github/min_example.tar.gz

It doesn't look to me like there is any real parallel data in that warc file, but if bitextor gets stuck on files like that, it blocks the whole process.

**Comment by critias** [comment]
It looks to me like there is a mismatch in the input to bitextor-align-documents.py
1.rank.xz contains 16 lines while there are 17 lines in the first url file.
I traced the problem back to bitextor-tokenize.py. One line/document is returned empty by the for some reason by the tokenzier, and the empty return value is then dropped by the bitextor-tokenize.py script. I haven't figured out yet why the return value is empty.

Besides that, is there a placeholder for dropped lines as a fallback if something fails?

Just adding an empty line causes the alignsegments_hunalign step to fail.
Trying to use the number of lines of the 1.rank.xz file causes a later step to fail (bifixer).

**Comment by zuny26** [comment]
You are right, the problem comes from bitextor-tokenize.py. The return value is empty because sentences that contain more digits/punctuation than letters are discarded. So if every sentence of a document is filtered by that rule, the output for that document is empty. This should be fixed in commit fc37591f715c46308505e2c95d94e856a88edb27.
With that fix, the example that you provided ran correctly, so your problem should be solved now.

**Comment by critias** [comment]
It works now, thank you!
Also thanks for changing bitextor-build-docalign.py to avoid this problem in the future.
