### ISSUE TITLE
Instruction on running bitextor_align_segments.py for Hunalign only?

### ISSUE THREAD

**Issue by kirklandWater1** [bitextor/bitextor#240]
Hi,

Thank you for the great tool!

I am trying to use **_bitextor_align_segments.py_** to run Hunalign on sentence alignment by the given Hunalign source and target examples. I have tried running the following command:  

`python bitextor_align_segments.py --hunalign hunalign/src/hunalign/hunalign hunalign/examples/demo.hu.stem hunalign/examples/demo.en.stem`

but I got **_`error: unrecognized arguments: hunalign/examples/demo.en.stem`_**

I was wondering if you can provide some instruction on can I do it.

Thanks!

**Comment by cgr71ii** [comment]
Hi!

The script `bitextor_align_segments.py` is expected to be used after the document aligner step, so it can't be used directly the way you want. I've adapted the command so you can use it the way you want:

```bash
echo -e "src_index\ttrg_index\tsrc_url\ttrg_url\tsrc_text\ttrg_text\tsrc_tokenized\ttrg_tokenized" \
  | cat - <(paste <(echo -e "1\t1\tdoc_hu\tdoc_en") \
                  <(cat hunalign/examples/demo.hu.stem | base64 -w 0) <(cat hunalign/examples/demo.en.stem | base64 -w 0) \
                  <(cat hunalign/examples/demo.hu.stem | base64 -w 0) <(cat hunalign/examples/demo.en.stem | base64 -w 0)) \
  | python bitextor_align_segments.py --hunalign "hunalign/src/hunalign/hunalign"
```

The only problem I've detected is that the examples from hunalign can't be correctly decoded to UTF-8 after decoding from BASE64, so `bitextor_align_segments.py` throws an error. In Bitextor this shouldn't happen since the selected preprocessor should deal with this kind of problems, but since you're providing your own files in one of the scripts, you should take care of this problems.
