### ISSUE TITLE
Document level granularity of Paracrawl

### ISSUE THREAD

**Issue by vince62s** [bitextor/bitextor#259]
Hi,

is there somewhere a release of Paracrawl with bitextor granularity "Document" instead of sentences.

if not what if the easiest way to reproduce those.

Cheers.

**Comment by ZJaume** [comment]
Hi @vince62s,

Unfortunately there's no data preserving that kind of information for Paracrawl. In the raw file, you might find the less filtered version we have. If you group by url, and in the same order they appear in the file, concatenating the sentences will give you some kind of "documents" but there will be sentences missing and the order might not be correct. But, if you are interested in document level and not particularly in the languages of Paracrawl, the parallel data from https://macocu.eu has been created with more recent Bitextor versions and the latest version of each language-pair has a `doc.txt` file available for download. In those files, you will find in the columns 3 and 4, a base64 encoded document. Note that you might need additional filtering, as this doc version is less filtered in order to preserve full documents.

**Comment by ZJaume** [comment]
I'm closing this. Feel free to re-open if you have any more doubts.

Just for your interest, the next bilingual release from HPLT we are cooking will come with the same paragraph identifiers as macocu and a document level output.
