### ISSUE TITLE
Problems with sentence splitting in ParaCrawl releases (v1.2 and v2.0)

### ISSUE THREAD

**Issue by achimr** [bitextor/bitextor#42]
Per https://github.com/paracrawl/Malign/issues/11

There are some issues with sentence splitting in the English-German v1.2 and v2.0 releases. I looked at the sets that were cleaned with Bicleaner. I noticed that the TMX files contain segments that are not properly sentence split:

* There are segments that contain 2 or more sentences (I have seen up to 5). The ones that I noticed have the same number of sentences on the source and target side, so they could be split into multiple segments. They are marked as 1:1 alignments in the property type. Examples are the TUIDs 97,101,112 and 116 in paracrawl-release1.2.en-de.withstats.filtered-bicleaner.tmx.gz and TUID 368175616 in paracrawl-release2.en-de.withstats.filtered-bicleaner.tmx.gz. There are many more - I ran the a sentence splitter that splits segments with an equal number of sentences on the ParaCrawl v1.2 data and obtained about 20 million sentence pairs instead of the 17 million directly extracted from the TMX.
* There is also the reverse case where a single sentence is distributed over a number of segments - e.g. the last 6 segments in paracrawl-release1.2.en-de.withstats.filtered-bicleaner.tmx.gz 317883035-317883040 contain a single sentence. I understand of course that with the difficulties of source document formatting and other non-sentence data on HTML pages these are hard to merge automatically.

**Comment by lpla** [comment]
Hi Achim.

Most of these examples should be fixed in latest Paracrawl releases and Bitextor code by now. This kind of issues were originated at several points in the Bitextor pipeline, which have been improved during these two years. Text extraction from PDFs now include a language model to amend wrong space detections, sentence splitter brings fixes from upstream, Malign has been rewritten completely, Bleualign joined sentences are better managed, and tools like `bifixer` and `bicleaner` keep progressing and polishing the general output quality.

We expect to release a new version of the Paracrawl corpus and Bitextor code very soon. Please, don't hesitate to report any kind of issue you get with any them, so we can keep refining the process.

Thank you.
