### ISSUE TITLE
Neural config variables are mandatory

### ISSUE THREAD

**Issue by lpla** [bitextor/bitextor#44]
When trying my config.json without nmt doc aligner error pops requesting 'marianDir' variable. Bitextor shouldn't use any nmt code if not specified, probably any of the last folder renaming changes made it mandatory accidentally?

**Comment by hieuhoang** [comment]
these 2 lines will kick off nmt training, they can be wrapped in if statements https://github.com/bitextor/bitextor/blob/577ef59ee70d96a1074a05f79cfa1b1a9e30087f/snakemake/Snakefile#L310

**Comment by lpla** [comment]
Miquel added an if. Now it works. Thanks!

**Comment by hieuhoang** [comment]
I've added a nmt variable instead of re-using the 'marek' document alignment variable
   https://github.com/bitextor/bitextor/commit/dc1fcf54e89dd1e4bd5542de381780528b62faca
I would want to see the NMT bleu scores even if I use some other document alignment

Now that the config file is growing, we should use explicit variable like 'nmt' 'tmx' for branching, rather than working out branching implicitly. It's too confusing
