### ISSUE TITLE
the bitextor.sh script problem : if [ $(echo $line | grep '\s' | wc -l) -eq 0 ]; 

### ISSUE THREAD

**Issue by JiaYueHuang** [bitextor/bitextor#53]
May be I found a problem in the bitextor.sh (I am not sure if I understand correctly):
The object of the following command in the bitextor.sh is to find the  blank line in the file which does not meet the required format.
in line num 888 of the bitextor.sh :           if [ $(echo $line | grep '\s' | wc -l) -eq 0 ]; 

but I think if there is a line that has the '\s' but not in the format such as "url   ett_file_path",  but in the format such as "url    " (missing the ett_file_path, but it also match the if sentence)

Maybe this is just a small problem, rarely encountered in practical applications

**Comment by lpla** [comment]
The string "url " does not match the if sentence. If you test this in `bash` it will return 1:

`echo "url " | grep '\s' | wc -l`

I think the "if" is working as intended (but it could be coded in a better way).

**Comment by JiaYueHuang** [comment]
The command you provided return 1, that is to say it matches; in other words, it indicate that the "url " contains the '\s' character (Null character)  and the grep command can find it and have one return ; and in line 888 of the bitextor.sh script, the logical meaing is :  if the command   $(echo $line | grep '\s' | wc -l)  return 0, that means the $line doesn't meet the correct format（In other words, if it return 1,that is to say it meet the correct format, but "url " isn't the correct format but it also will return 1）.

**Comment by lpla** [comment]
The example "url " has a correct format. The expression matches because the format is the one we expect: `data TAB data`. I agree with you that data in the fields are not right, because the second field is empty in our example (field 1: `url`, fields 2: `""`. But we are not checking the fields data here, we are only checking format, and, again, the format is correct, so the 'if' works as intended.

If you are worried about the fields content, I want you to know that they are checked and managed in the Python scrips, raising exceptions if a path or URL is not right. Again, in our example, it will raise an exception saying that the ETT is empty or not found.

Thanks for your feedback and don't hesitate to ask or make a pull request anytime.

**Comment by JiaYueHuang** [comment]
Oh, I see. Thanks very much.
